version: '3.8'

services:
  # Backend
  backend:
    build: ./backend
    container_name: finview-backend
    ports:
      - "8080:8080"
    environment:
      - SECRET=${SECRET} 
      
      - PORT=8080 
      
     
      - DB=/app/database/finview.db
    volumes:
      - ./database:/app/database
    restart: unless-stopped

    env_file:
      - ./backend/.env

  # Frontend
  frontend:
    build: ./frontend
    container_name: finview-frontend
    ports:
      - "3000:80" 
    depends_on:
      - backend 
    restart: unless-stopped
