version: '3.8'

services:
  #Backend build
  backend:
    build: ./backend
    container_name: finview-backend
    ports:
      - "8080:8080"
    environment:
      - SECRET=SuaChaveSecretaSuperSeguraAqui
      - PORT=8080
    volumes:
    
      - ./backend:/app 
    restart: unless-stopped #To make database persist

  # Front build
  frontend:
    build: ./frontend
    container_name: finview-frontend
    ports:
      - "3000:80" 
    depends_on:
      - backend 
    restart: unless-stopped